- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
  # - include: tasks/test.yml
  - include: tasks/ssh.yml
  - include: tasks/zsh.yml
  - include: tasks/dotfiles.yml
  - include: tasks/core-setup.yml
  - include: tasks/asdf.yml
  - include: tasks/npm-packages.yml
  - include: tasks/neovim.yml
  - include: tasks/slack.yml
  - include: tasks/chrome.yml
  - include: tasks/notion.yml
  - include: tasks/dev-tools.yml
    # general tools (slack, notion-enhanced, chrome, nerd-fonts(meso))
    # dev tools (insomnia, dbeaver, tmux, lazygit, i3wm, gnome-tweaks)
