- name: Download asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.10.0
  tags:
    - asdf
    - install
# - name: Set asdf and source .bashrc
#   shell: cd $HOME && echo '. $HOME/.asdf/asdf.sh' >> .bashrc
#   tags:
#     - asdf
#     - install
- name: Install asdf NodeJs plugin dependencies
  become: true
  apt:
    name: ["dirmngr", "gpg", "curl", "gawk"]
  tags:
    - asdf
    - node
    - install
- name: Install asdf NodeJs Plugin
  shell: source ~/.zshrc && asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  args:
    executable: /usr/bin/zsh # Run in the zsh
  tags:
    - install
    - asdf
    - node
- name: Install nodejs 16.15.1LTS
  shell: source ~/.zshrc && asdf install nodejs 16.15.1
  args:
    executable: /usr/bin/zsh 
  tags:
    - install
    - asdf
    - node
- name: Set Node 16 as global
  shell: source ~/.zshrc && asdf global nodejs 16.15.1
  args:
    executable: /usr/bin/zsh 
  tags:
    - install
    - asdf
    - node
