- name: Install System Packages 1 (build-essential, cmake, pkgconfig, pthread, xclip)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev", "xclip", "wget"]
  tags:
    - install
    - neovim
    - core
- name: Install System Packages 2 (mostly neovim req)
  become: true
  apt:
    name: ["ninja-build", "gettext", "libtool", "libtool-bin", "autoconf", "automake", "g++", "pkg-config", "unzip", "doxygen", "neofetch"]
  tags:
    - install
    - neovim
    - core
