- name: Install Dbeaver dependencies
  become: true
  apt:
    name: "default-jdk"
    state: present
  tags:
    - install
    - dbeaver
- name: Add Dbeaver GPG key
  become: true
  shell: wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
  tags:
    - install
    - dbeaver
- name: Setup the Dbeaver repository
  become: true
  shell: echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
  tags:
    - dbeaver
    - install
- name: Apt update 
  become: true
  apt:
    update_cache: yes
  tags:
    - dbeaver
    - install
- name: Install Dbeaver
  become: true
  apt:
    name: dbeaver-ce
  tags:
    - install
    - dbeaver
