- name: Install dev packages (tmux, gnome-tweaks)
  become: true
  apt:
    name: [ "tmux", "gnome-tweaks"]
  tags:
    - install
    - dev
    - tmux
- name: Download tmux tpm plugin manager
  become: true
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
  tags:
    - install
    - tmux
    - dev

- name: Install i3wm
  become: true
  apt:
    name: i3
    state: present
  tags:
    - dev
    - install
    - i3
- name: Install i3blocks
  become: true
  apt:
    name: i3blocks
    state: present
  tags:
    - dev
    - install
    - i3
- name: Install imagemagick and scrot (i3lock script dep)
  become: true
  apt:
    name: ["imagemagick", "scrot", "xautolock"]
  tags:
    - dev
    - install
    - i3

- name: Install fzf
  become: true
  apt:
    name: fzf 
  tags:
    - fzf
    - install
    - dev

# - name: Install LazyGit
#   shell: source ~/.zshrc && go install github.com/jesseduffield/lazygit@latest
#   args:
#     executable: /usr/bin/zsh
#   tags:
#     - install
#     - dev
#     - lazygit

- name: Add insomnia repository 
  become: true
  shell: echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" | sudo tee -a /etc/apt/sources.list.d/insomnia.list
  tags:
    - dev
    - install
    - insomnia
- name: Apt update 
  become: true
  apt:
    update_cache: yes
  tags:
    - insomnia
    - dev
    - install
- name: Install insomnia
  become: true
  apt:
    name: insomnia 
  tags:
    - insomnia
    - install
    - dev
