- name: Install dev packages (tmux, gnome-tweaks)
  become: true
  apt:
    name: [ "tmux", "gnome-tweaks"]
  tags:
    - install
    - dev
    - tmux
- name: Download tmux tpm plugin manager
  become: true
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
  tags:
    - install
    - tmux
    - dev

- name: Install i3wm
  become: true
  apt:
    name: i3
    state: present
  tags:
    - dev
    - install
    - i3
- name: Install i3blocks
  become: true
  apt:
    name: i3blocks
    state: present
  tags:
    - dev
    - install
    - i3
- name: Install imagemagick and scrot (i3lock script dep)
  become: true
  apt:
    name: ["imagemagick", "scrot", "xautolock"]
  tags:
    - dev
    - install
    - i3

- name: Install fzf
  become: true
  apt:
    name: fzf 
  tags:
    - fzf
    - install
    - dev

- name: Install lazygit
  shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    sudo tar xf lazygit.tar.gz -C /usr/local/bin lazygit
  tags:
    - install
    - dev
    - lazygit

- name: Add insomnia repository 
  become: true
  shell: echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" | sudo tee -a /etc/apt/sources.list.d/insomnia.list
  tags:
    - dev
    - install
    - insomnia
- name: Apt update 
  become: true
  apt:
    update_cache: yes
  tags:
    - insomnia
    - dev
    - install
- name: Install insomnia
  become: true
  apt:
    name: insomnia 
  tags:
    - insomnia
    - install
    - dev
