- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
    - neovimreinstall
- name: Get Packer
  become: true
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
- name: Permission on the local
  become: true
  shell: "chmod -R a+xrw {{ lookup('env', 'HOME') }}/.local/share/nvim"
  tags:
    - install
    - neovim
- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    version: 'stable'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
    - neovimreinstall
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - install
    - neovim
    - neovimreinstall
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim
    - neovimreinstall

- name: Install TS LSP
  shell: source ~/.zshrc && npm install --global typescript-language-server
  args:
    executable: /usr/bin/zsh 
  tags:
    - npm
    - install
    - tsserver 


- name: Install Go LSP
  shell: source ~/.zshrc && go install golang.org/x/tools/gopls@latest 
  args:
    executable: /usr/bin/zsh 
  tags:
    - npm
    - install
    - gopls 
