- name: Add notion-repackaged repository 
  become: true
  shell: echo "deb [trusted=yes] https://apt.fury.io/notion-repackaged/ /" | sudo tee /etc/apt/sources.list.d/notion-repackaged.list
  tags:
    - notion
    - install
- name: Apt update 
  become: true
  apt:
    update_cache: yes
  tags:
    - notion
    - install
- name: Install notion-enhanced
  become: true
  apt:
    name: notion-app-enhanced
  tags:
    - notion
    - install
