- name: Install dconf if not installed
  become: true
  apt:
    name: ["dconf-cli", "dconf-service", "dconf-gsettings-backend"]
    state: present
  tags:
    - terminal
    - install
    - themes

- name: Installing custom themes 
  become: true
  shell: ./terminalThemeInstall.sh
  tags:
    - install
    - terminal
    - themes

- name: Setting the default theme
  shell: source ~/.zshrc && node ./defaultTheme.js "{{ terminal_theme }}" 
  args:
    executable: /usr/bin/zsh 
  tags:
    - install
    - terminal
    - themes

- name: Change Ubuntu theme
  become: true
  shell: gsettings set org.gnome.desktop.interface gtk-theme {{ ubuntu_theme }}
  ignore_errors: true
  tags:
    - install
    - themes
    - ubuntu
